# Generated by Django 4.2.3 on 2023-07-16 01:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Kategori Adı')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, help_text='Maksimum 200 karakter', max_length=200, verbose_name='Kısa Açıklama')),
                ('seoTitle', models.CharField(blank=True, max_length=160, verbose_name='SEO Başlığı')),
                ('seoKeywords', models.TextField(blank=True, verbose_name='Anahtar Kelimeler')),
                ('seoDescription', models.TextField(blank=True, verbose_name='SEO Açıklama')),
                ('createdOn', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updatedOn', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('status', models.IntegerField(choices=[(0, 'Taslak'), (1, 'Yayınla')], default=1, verbose_name='Durum')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yazar')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
                'ordering': ['-createdOn'],
            },
        ),
    ]
