# Generated by Django 4.2.3 on 2023-07-16 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_category_seodescription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.IntegerField(choices=[(0, 'Taslak'), (1, 'Yayında')], default=1, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(0, 'Taslak'), (1, 'Yayında')], default=1, verbose_name='Durum'),
        ),
    ]
